### ISSUE TITLE
More items to group

### ISSUE THREAD

**Issue by sternschnaube** [KessokuTeaTime/REI-Collapsible-Entries#1]
Wonderful mod - more items came to my mind, where I think it would be good if they would also be grouped.

- Wool blocks
- Light blocks (15 - 1)
- Wool carpets
- Stained Glass blocks
- Sword and tools, everything together
- Armor parts, everything together
- Dead coral blocks
- Coral blocks
- Sapplings
- Flowers 
- Skull blocks
- Horse Armor
- All 4 rail types

Looking forward to hear what do you think about my ideas 😊

Another tiny thing: A second expand option, with custom key support. In my case: the middle mouse button, and or double-click with left and right.

**Comment by KrLite** [comment]
Good ideas! The entries you mentioned will surely be added soon.

But, the shortcut feature to uncollapse entries are actually a bit hard to implement as **this collapsible entry feature is provided by REI itself, so does the shortcuts.** But, as we're concerned, almost none of the mods registers the entries themselves. So this mod is here to help. To sum up, the shortcut feature should be addressed to REI.

**Comment by KrLite** [comment]
Almost done! What's more: the tools and armors are now not only sorted by types, but also by materials! Which means you can find `Leather Cap` in both `Leather Armors` and `Caps and Helmets` entries.

<img width="660" alt="image" src="https://github.com/KrLite/REI-Collapsible-Entries-QOL/assets/68179735/130b0084-41f2-439a-889a-87e9d963d830">

**Comment by KrLite** [comment]
It seems that all the entries you suggested are implemented now. Fell free to suggest more!

**Comment by KrLite** [comment]
All done! Check it [here.](https://modrinth.com/mod/rei-collapsible-entries/version/1.0.1-mc1.20)

**Comment by venaminecraft** [comment]
Wow! I was not even thinking to group under a group, which seems really nice 😊

I will check the mod soon out. You can only group items from internal order?

Like if I would wanna combine all food items at once. Just as example.

**Comment by KrLite** [comment]
> Wow! I was not even thinking to group under a group, which seems really nice 😊
> 
> I will check the mod soon out. You can only group items from internal order?
> 
> Like if I would wanna combine all food items at once. Just as example.

Well actually... nested groups are not allowed by **REI** 😢. I'm sorry if the picture confuses you. Generally speaking, the picture is showing the same items being included in different groups.

And, could you please explain again what you mean by *internal order?*

**Comment by venaminecraft** [comment]
Sorry for the late response ☺️ 

Ah, I see, it's still fine and the benefit is there.

"Internal order" - the item grouping starts with Stone, Granite, and so on.
Does this order matters for the grouping? Or can you simple counting every item. 
Example: I group Stone with Pumpkin, where the Pumpkin comes far later.

Other ideas: Minecarts, Firework Rockets.



You forgot to put the Mangrove Sappling:D

![image](https://github.com/KrLite/REI-Collapsible-Entries-QOL/assets/120551916/25f9dd6f-26f9-4974-ac66-f6c7358d9a55)

**Comment by KrLite** [comment]
I see! Well, **REI** allows us to group items despite of their internal order. However, the groups' order may seem to be internal, but that doesn't matter :)
And the mangrove sapling, maybe I was too careless to include it as I actually group items according to their tags or identifiers (which enables more flexibility)... And I believe it was caused by its 'unique' identifier set by Mojang. Mojang always does such things. I'll fix it soon.

**Comment by venaminecraft** [comment]
It's great that the internal orders plays no role.

I would put the Ancient Debris into the Ores aswell.

![image](https://github.com/KrLite/REI-Collapsible-Entries-QOL/assets/120551916/d165541d-46e0-4167-8aaf-85bdff693cf9)

And new ideas: 

- Minecarts (huh, I forgot them), Commandblock Minecart too, comes later*
- Block of Raw Iron, Copper, Gold
- Block of Coal, Amethyst, Iron, Copper (Waxed), Gold, Diamond, Netherite, Lapis
- All three Anvil types
- Amethyst Cluster

I think that's really **all** - it's amazing how compact everything is now ☺️

**Comment by KrLite** [comment]
That's great! I'm rewriting the parsing logics so it may take some time, but certainly not too long.

**Comment by venaminecraft** [comment]
I will keep my eyes on it 😄

**Comment by KrLite** [comment]
Sorry that I'm too busy to finish my work. Optimistically, you will meet the next release this weekend.

**Comment by venaminecraft** [comment]
You have all the time 😊
I'm happy to use the updated version soon 🥳

**Comment by KrLite** [comment]
Here it is! https://modrinth.com/mod/rei-collapsible-entries/version/2.0.0-mc1.20

**Comment by venaminecraft** [comment]
Yay!! ☺️
Thanks for your hard work.
